### ISSUE TITLE
SyntaxError: unknown encoding: future_fstrings

### ISSUE THREAD

**Issue by fizwit** [flying-sheep/get_version#4]
### Issue
```
>>> import get_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/easybuild/software/Python/3.7.4-foss-2016b/lib/python3.7/site-packages/get_version.py", line 0
SyntaxError: unknown encoding: future_fstrings
```
### Environment
Linux Ubuntu, Python 3.7.4

### Install
```
pip install get_version
Collecting get_version
  Using cached https://files.pythonhosted.org/packages/2d/27/610ef458455cb1bcc4b454cebab43de3579e43d080af872727b9ac3146c8/get_version-2.0.6-py3-none-any.whl
Requirement already satisfied: setuptools in /app/easybuild/software/Python/3.7.4-foss-2016b/lib/python3.7/site-packages (from get_version) (40.8.0)
Requirement already satisfied: future-fstrings in /app/easybuild/software/Python/3.7.4-foss-2016b-fh1/lib/python3.7/site-packages (from get_version) (1.2.0)
Installing collected packages: get-version
Successfully installed get-version-2.0.6
```

**Comment by flying-sheep** [comment]
I see `Requirement already satisfied: future-fstrings`, so you have that encoding already installed. No idea what goes wrong here, but if it’s a bug and not a problem with your setup, it’s a bug in `future-fstrings`, not `get_version`.
