### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by falexwolf** [flying-sheep/get_version#5]
Python 3.7 install in a conda environment. Trying to install scgen following https://scgen.readthedocs.io/en/latest/installation/.
```
Traceback (most recent call last):
  File "/home/ubuntu/data/miniconda3/bin/flit", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/__init__.py", line 122, in main
    pth=args.pth_file).install()
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/install.py", line 395, in install
    self.install_with_pip()
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/install.py", line 328, in install_with_pip
    wb = WheelBuilder(self.ini_path, fp)
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/wheel.py", line 47, in __init__
    self.metadata = common.make_metadata(self.module, self.ini_info)
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/common.py", line 302, in make_metadata
    md_dict.update(get_info_from_module(module))
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/common.py", line 113, in get_info_from_module
    docstring, version = get_docstring_and_version_via_import(target)
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/flit/common.py", line 97, in get_docstring_and_version_via_import
    m = sl.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "scgen/__init__.py", line 18, in <module>
    from get_version import get_version
  File "/home/ubuntu/data/miniconda3/lib/python3.7/site-packages/get_version.py", line 0
SyntaxError: unknown encoding: future_fstrings
```

**Comment by flying-sheep** [comment]
Maybe you use an old pip version that doesn’t install the build requirements before installing the package:

https://github.com/flying-sheep/get_version/blob/1042779cdbf15b3c971744a5dae780706af3433b/pyproject.toml#L1-L3

Anyway I can’t reproduce:

```console
$ python -m venv test-get-version
$ . ./test-get-version/bin/activate
$ pip --version
pip 19.2.3 from ~/test-get-version/lib/python3.7/site-packages/pip (python 3.7)
$ pip install get_version
Collecting get_version
  Downloading https://files.pythonhosted.org/…/get_version-2.0.6-py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 2.6MB/s 
Collecting future-fstrings (from get_version)
  Downloading https://files.pythonhosted.org/…/future_fstrings-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./test-get-version/lib/python3.7/site-packages (from get_version) (40.8.0)
Installing collected packages: future-fstrings, get-version
Successfully installed future-fstrings-1.2.0 get-version-2.0.6
```

**Comment by falexwolf** [comment]
Hm. It's a brand new pip and python install based on the latest Miniconda3 (yesterday). Everything else works perfectly.

**Comment by falexwolf** [comment]
Could be the interaction with conda...

**Comment by flying-sheep** [comment]
Could be. I can’t reproduce this with PyPI, and the workaround is very simple, so I don’t consider this a priority.

That said, I’m getting rid of Python 3.5 compatibility in my packages (which we started with scanpy) and therefore also there’s no need for future_fstrings.
